default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: '.*\.(yaml)$'
      - id: sort-simple-yaml
        files: '.*\.(yaml)$'
      - id: check-toml
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
        args: [--max-line-length=88]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: ""
    hooks:
      - id: pydocstyle
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
  - repo: https://github.com/prettier/prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
