default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        files: '.*\.(yaml)$'
    -   id: sort-simple-yaml
        files: '.*\.(yaml)$'
    -   id: check-toml
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=88]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
