name: Run Checks
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-poetry-action@v1.3

      - name: Poetry
        run: poetry install

      - name: Black
        run: poetry run black --target-version py38 . --check

      - name: Flake8
        run: poetry run flake8
      
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.0
        with:
          # 
          github-token: github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to lcov file
          path-to-lcov: # default is ./coverage/lcov.info
          # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
          parallel: # optional
          # Set to true for the last action when using "parallel: true".
          parallel-finished: # optional
          # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
          coveralls-endpoint: # optional, default is https://coveralls.io
          # The root folder of the project that originally ran the tests
          base-path: # optional
        
